import '../../data/models/match_analysis_model.dart';

/// Mock matches for the Manager Matches screen. These mirror the AI output
/// shape used throughout the app so they can be passed directly to the
/// existing MatchAnalysisScreen via router extras.

final List<MatchAnalysisModel> kManagerMockMatches = [
  const MatchAnalysisModel(
    matchId: 'm-20260503-01',
    homeTeam: 'Red Lions',
    awayTeam: 'Blue Hawks',
    score: '3 - 1',
    date: '2026-05-03',
    status: 'FT',
    players: [
      PlayerModel(
        id: 'p1',
        name: 'Omar Salah',
        position: 'FW',
        rating: 8.6,
        fatigue: 28,
        performanceStatus: PerformanceStatus.excellent,
        insight: 'Clinical finishing and great movement.',
        contribution: ContributionType.attack,
        impact: 'Game Changer',
        goals: 2,
        assists: 0,
        isMOTM: true,
      ),
      PlayerModel(
        id: 'p2',
        name: 'Tariq Samir',
        position: 'MF',
        rating: 7.8,
        fatigue: 34,
        performanceStatus: PerformanceStatus.good,
        insight: 'Drove attacks from midfield.',
        contribution: ContributionType.balanced,
        impact: 'Reliable',
      ),
    ],
    homeAnalysis: TeamAnalysisModel(
      teamName: 'Red Lions',
      possession: 62,
      style: 'Possession-based',
      pressureStyle: 'Mid Block',
      compactness: 'Compact',
      attackingZones: ['Left Wing', 'Central'],
      avgRating: 7.6,
      topPlayers: ['p1'],
      worstPlayers: [],
    ),
    awayAnalysis: TeamAnalysisModel(
      teamName: 'Blue Hawks',
      possession: 38,
      style: 'Counter-attack',
      pressureStyle: 'Low Block',
      compactness: 'Wide',
      attackingZones: ['Right Wing'],
      avgRating: 6.1,
      topPlayers: [],
      worstPlayers: [],
    ),
    summary: MatchSummaryModel(
      dominantTeam: 'Red Lions',
      homeAvgRating: 7.6,
      awayAvgRating: 6.1,
      motmPlayerId: 'p1',
      worstPlayerId: '',
      keyMoments: ["23' Goal - Omar Salah", "78' Penalty - Saved"],
      overallNarrative: 'Red Lions controlled possession and punished mistakes.',
    ),
    recommendations: ['Rotate tired fullback', 'Work on set-piece marking'],
    highlightText: 'Strong possession display',
    intensity: 56,
  ),

  const MatchAnalysisModel(
    matchId: 'm-20260425-02',
    homeTeam: 'Green Falcons',
    awayTeam: 'Red Lions',
    score: '1 - 2',
    date: '2026-04-25',
    status: 'FT',
    players: [
      PlayerModel(
        id: 'p3',
        name: 'Mahmoud Ali',
        position: 'DF',
        rating: 6.9,
        fatigue: 45,
        performanceStatus: PerformanceStatus.average,
        insight: 'Solid but exposed on counters.',
        contribution: ContributionType.defense,
        impact: 'Steady',
      ),
    ],
    homeAnalysis: TeamAnalysisModel(
      teamName: 'Green Falcons',
      possession: 49,
      style: 'Balanced',
      pressureStyle: 'Mid Block',
      compactness: 'Wide',
      attackingZones: ['Central'],
      avgRating: 6.7,
      topPlayers: [],
      worstPlayers: [],
    ),
    awayAnalysis: TeamAnalysisModel(
      teamName: 'Red Lions',
      possession: 51,
      style: 'Balanced',
      pressureStyle: 'High Press',
      compactness: 'Compact',
      attackingZones: ['Left Wing'],
      avgRating: 7.1,
      topPlayers: [],
      worstPlayers: [],
    ),
    summary: MatchSummaryModel(
      dominantTeam: 'Red Lions',
      homeAvgRating: 6.7,
      awayAvgRating: 7.1,
      motmPlayerId: '',
      worstPlayerId: '',
      keyMoments: ["10' Early goal", "85' Winner"],
      overallNarrative: 'Tight game decided late by a clinical finish.',
    ),
    recommendations: ['Improve transition defence'],
    highlightText: null,
    intensity: 62,
  ),

  const MatchAnalysisModel(
    matchId: 'm-20260310-03',
    homeTeam: 'Blue Hawks',
    awayTeam: 'Green Falcons',
    score: '0 - 0',
    date: '2026-03-10',
    status: 'FT',
    players: [],
    homeAnalysis: TeamAnalysisModel(
      teamName: 'Blue Hawks',
      possession: 50,
      style: 'Counter-attack',
      pressureStyle: 'Low Block',
      compactness: 'Deep',
      attackingZones: ['Right Wing'],
      avgRating: 6.2,
      topPlayers: [],
      worstPlayers: [],
    ),
    awayAnalysis: TeamAnalysisModel(
      teamName: 'Green Falcons',
      possession: 50,
      style: 'Balanced',
      pressureStyle: 'Mid Block',
      compactness: 'Wide',
      attackingZones: ['Central'],
      avgRating: 6.2,
      topPlayers: [],
      worstPlayers: [],
    ),
    summary: MatchSummaryModel(
      dominantTeam: 'None',
      homeAvgRating: 6.2,
      awayAvgRating: 6.2,
      motmPlayerId: '',
      worstPlayerId: '',
      keyMoments: [],
      overallNarrative: 'Closely contested goalless draw.',
    ),
    recommendations: [],
    highlightText: null,
    intensity: 44,
  ),
];
