// ---------------------------------------------------------------------------
// GoalSight — Players Mock Data
//
// Generates realistic player profile data with historical ratings,
// match history, and AI-generated insights.
// Simulates data aggregated from multiple match analyses.
// ---------------------------------------------------------------------------

import 'package:goal_sight/data/models/player_profile_model.dart';

final List<PlayerProfileModel> kManagerMockPlayers = [
  // Defender
  PlayerProfileModel(
    id: 'p001',
    name: 'Marcus Johnson',
    position: 'DEF / LWB',
    currentRating: 7.8,
    averageRating: 7.5,
    fatigue: 45,
    activityLevel: 72,
    primaryContribution: 'Defense',
    secondaryContribution: 'Attack',
    status: 'In Form',
    improvementRate: 8.5,
    trend: PerformanceTrend.improving,
    totalMatches: 12,
    totalGoals: 1,
    totalAssists: 2,
    totalTackles: 34,
    ratingsHistory: [6.8, 7.2, 7.5, 7.6, 7.7, 7.8, 7.9, 7.8],
    insights: [
      'Excellent defensive positioning',
      'Improving crossing accuracy',
      'High work rate in transitions',
      'Left-sided dominance',
    ],
    matchHistory: [
      PlayerMatchHistory(
        matchId: 'm001',
        matchDate: DateTime(2026, 5, 2),
        homeTeam: 'Red Lions',
        awayTeam: 'Green Falcons',
        playerRating: 7.8,
        performanceStatus: 'Excellent',
        goals: 0,
        assists: 1,
        tackles: 5,
        keyPasses: 3,
      ),
      PlayerMatchHistory(
        matchId: 'm002',
        matchDate: DateTime(2026, 4, 28),
        homeTeam: 'Red Lions',
        awayTeam: 'Blue Strikers',
        playerRating: 7.6,
        performanceStatus: 'Good',
        goals: 0,
        assists: 0,
        tackles: 4,
        keyPasses: 2,
      ),
      PlayerMatchHistory(
        matchId: 'm003',
        matchDate: DateTime(2026, 4, 24),
        homeTeam: 'Red Lions',
        awayTeam: 'Yellow Hawks',
        playerRating: 7.5,
        performanceStatus: 'Good',
        goals: 1,
        assists: 1,
        tackles: 3,
        keyPasses: 4,
      ),
    ],
  ),
  
  // Midfielder
  PlayerProfileModel(
    id: 'p002',
    name: 'Alex Rivera',
    position: 'MID / CM',
    currentRating: 8.2,
    averageRating: 8.0,
    fatigue: 52,
    activityLevel: 85,
    primaryContribution: 'Balanced',
    secondaryContribution: 'Attack',
    status: 'Elite Form',
    improvementRate: 5.2,
    trend: PerformanceTrend.stable,
    totalMatches: 12,
    totalGoals: 3,
    totalAssists: 5,
    totalTackles: 18,
    ratingsHistory: [7.9, 8.0, 8.1, 8.0, 8.2, 8.2, 8.1, 8.2],
    insights: [
      'Game-changing distribution',
      'Exceptional ball retention (89%)',
      'High-intensity pressing (15 pressures/match avg)',
      'Progressive passing specialist',
    ],
    matchHistory: [
      PlayerMatchHistory(
        matchId: 'm001',
        matchDate: DateTime(2026, 5, 2),
        homeTeam: 'Red Lions',
        awayTeam: 'Green Falcons',
        playerRating: 8.2,
        performanceStatus: 'Excellent',
        goals: 1,
        assists: 2,
        tackles: 2,
        keyPasses: 8,
      ),
      PlayerMatchHistory(
        matchId: 'm002',
        matchDate: DateTime(2026, 4, 28),
        homeTeam: 'Red Lions',
        awayTeam: 'Blue Strikers',
        playerRating: 8.0,
        performanceStatus: 'Excellent',
        goals: 0,
        assists: 1,
        tackles: 3,
        keyPasses: 7,
      ),
      PlayerMatchHistory(
        matchId: 'm003',
        matchDate: DateTime(2026, 4, 24),
        homeTeam: 'Red Lions',
        awayTeam: 'Yellow Hawks',
        playerRating: 7.9,
        performanceStatus: 'Good',
        goals: 2,
        assists: 2,
        tackles: 2,
        keyPasses: 6,
      ),
    ],
  ),

  // Attacker
  PlayerProfileModel(
    id: 'p003',
    name: 'Samuel Okoro',
    position: 'ATT / ST',
    currentRating: 8.5,
    averageRating: 8.1,
    fatigue: 58,
    activityLevel: 78,
    primaryContribution: 'Attack',
    secondaryContribution: 'Balanced',
    status: 'Explosive Form',
    improvementRate: 12.3,
    trend: PerformanceTrend.improving,
    totalMatches: 11,
    totalGoals: 9,
    totalAssists: 3,
    totalTackles: 8,
    ratingsHistory: [7.2, 7.5, 7.8, 8.0, 8.2, 8.4, 8.5],
    insights: [
      'Clinical finishing (45% conversion rate)',
      'Strong aerial dominance',
      'Creating space for teammates',
      'Recovery pace impressive after injury',
    ],
    matchHistory: [
      PlayerMatchHistory(
        matchId: 'm001',
        matchDate: DateTime(2026, 5, 2),
        homeTeam: 'Red Lions',
        awayTeam: 'Green Falcons',
        playerRating: 8.5,
        performanceStatus: 'Excellent',
        goals: 2,
        assists: 0,
        tackles: 1,
        keyPasses: 3,
      ),
      PlayerMatchHistory(
        matchId: 'm002',
        matchDate: DateTime(2026, 4, 28),
        homeTeam: 'Red Lions',
        awayTeam: 'Blue Strikers',
        playerRating: 8.2,
        performanceStatus: 'Excellent',
        goals: 1,
        assists: 1,
        tackles: 2,
        keyPasses: 2,
      ),
      PlayerMatchHistory(
        matchId: 'm003',
        matchDate: DateTime(2026, 4, 24),
        homeTeam: 'Red Lions',
        awayTeam: 'Yellow Hawks',
        playerRating: 8.0,
        performanceStatus: 'Good',
        goals: 1,
        assists: 1,
        tackles: 1,
        keyPasses: 1,
      ),
    ],
  ),

  // Goalkeeper
  PlayerProfileModel(
    id: 'p004',
    name: 'David Chen',
    position: 'GK',
    currentRating: 7.3,
    averageRating: 7.1,
    fatigue: 38,
    activityLevel: 65,
    primaryContribution: 'Defense',
    secondaryContribution: 'Balanced',
    status: 'Needs Improvement',
    improvementRate: -2.1,
    trend: PerformanceTrend.declining,
    totalMatches: 12,
    totalGoals: 0,
    totalAssists: 0,
    totalTackles: 5,
    ratingsHistory: [7.5, 7.4, 7.2, 7.2, 7.1, 7.0, 7.3],
    insights: [
      'Distribution accuracy declining',
      'Handling under pressure inconsistent',
      'Quick reflexes on close-range shots',
      'Communication with defense needs improvement',
    ],
    matchHistory: [
      PlayerMatchHistory(
        matchId: 'm001',
        matchDate: DateTime(2026, 5, 2),
        homeTeam: 'Red Lions',
        awayTeam: 'Green Falcons',
        playerRating: 7.3,
        performanceStatus: 'Average',
        goals: 0,
        assists: 0,
        tackles: 1,
        keyPasses: 0,
      ),
      PlayerMatchHistory(
        matchId: 'm002',
        matchDate: DateTime(2026, 4, 28),
        homeTeam: 'Red Lions',
        awayTeam: 'Blue Strikers',
        playerRating: 7.0,
        performanceStatus: 'Average',
        goals: 0,
        assists: 0,
        tackles: 2,
        keyPasses: 0,
      ),
      PlayerMatchHistory(
        matchId: 'm003',
        matchDate: DateTime(2026, 4, 24),
        homeTeam: 'Red Lions',
        awayTeam: 'Yellow Hawks',
        playerRating: 7.2,
        performanceStatus: 'Average',
        goals: 0,
        assists: 0,
        tackles: 2,
        keyPasses: 0,
      ),
    ],
  ),

  // Midfielder 2
  PlayerProfileModel(
    id: 'p005',
    name: 'Liam O\'Brien',
    position: 'MID / CAM',
    currentRating: 7.6,
    averageRating: 7.4,
    fatigue: 48,
    activityLevel: 80,
    primaryContribution: 'Attack',
    secondaryContribution: 'Balanced',
    status: 'In Form',
    improvementRate: 6.8,
    trend: PerformanceTrend.improving,
    totalMatches: 12,
    totalGoals: 2,
    totalAssists: 4,
    totalTackles: 12,
    ratingsHistory: [7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6],
    insights: [
      'Creative playmaking in final third',
      'Dribbling success rate improving',
      'Set-piece delivery consistent',
      'Tracking back defensively strong',
    ],
    matchHistory: [
      PlayerMatchHistory(
        matchId: 'm001',
        matchDate: DateTime(2026, 5, 2),
        homeTeam: 'Red Lions',
        awayTeam: 'Green Falcons',
        playerRating: 7.6,
        performanceStatus: 'Good',
        goals: 0,
        assists: 1,
        tackles: 1,
        keyPasses: 5,
      ),
      PlayerMatchHistory(
        matchId: 'm002',
        matchDate: DateTime(2026, 4, 28),
        homeTeam: 'Red Lions',
        awayTeam: 'Blue Strikers',
        playerRating: 7.5,
        performanceStatus: 'Good',
        goals: 1,
        assists: 1,
        tackles: 2,
        keyPasses: 4,
      ),
      PlayerMatchHistory(
        matchId: 'm003',
        matchDate: DateTime(2026, 4, 24),
        homeTeam: 'Red Lions',
        awayTeam: 'Yellow Hawks',
        playerRating: 7.4,
        performanceStatus: 'Good',
        goals: 1,
        assists: 2,
        tackles: 2,
        keyPasses: 4,
      ),
    ],
  ),

  // Defender 2
  PlayerProfileModel(
    id: 'p006',
    name: 'James Patterson',
    position: 'DEF / CB',
    currentRating: 7.4,
    averageRating: 7.3,
    fatigue: 42,
    activityLevel: 68,
    primaryContribution: 'Defense',
    secondaryContribution: 'Balanced',
    status: 'Stable',
    improvementRate: 1.2,
    trend: PerformanceTrend.stable,
    totalMatches: 12,
    totalGoals: 0,
    totalAssists: 1,
    totalTackles: 42,
    ratingsHistory: [7.2, 7.2, 7.3, 7.3, 7.4, 7.4],
    insights: [
      'Consistent defensive block',
      'Header dominance (87% win rate)',
      'Positional awareness excellent',
      'Concentration under pressure solid',
    ],
    matchHistory: [
      PlayerMatchHistory(
        matchId: 'm001',
        matchDate: DateTime(2026, 5, 2),
        homeTeam: 'Red Lions',
        awayTeam: 'Green Falcons',
        playerRating: 7.4,
        performanceStatus: 'Good',
        goals: 0,
        assists: 0,
        tackles: 6,
        keyPasses: 1,
      ),
      PlayerMatchHistory(
        matchId: 'm002',
        matchDate: DateTime(2026, 4, 28),
        homeTeam: 'Red Lions',
        awayTeam: 'Blue Strikers',
        playerRating: 7.3,
        performanceStatus: 'Good',
        goals: 0,
        assists: 0,
        tackles: 5,
        keyPasses: 1,
      ),
      PlayerMatchHistory(
        matchId: 'm003',
        matchDate: DateTime(2026, 4, 24),
        homeTeam: 'Red Lions',
        awayTeam: 'Yellow Hawks',
        playerRating: 7.3,
        performanceStatus: 'Good',
        goals: 0,
        assists: 1,
        tackles: 5,
        keyPasses: 0,
      ),
    ],
  ),
];
