import 'upload_job_model.dart';

final List<UploadJobModel> kMockUploadHistory = [
  UploadJobModel(
    id: 'job-001',
    homeTeam: 'GoalSight FC',
    awayTeam: 'Falcons United',
    competition: 'Premier League',
    venue: 'GoalSight Arena',
    matchDate: DateTime(2025, 5, 2),
    fileName: 'match_goalsight_vs_falcons_may2.mp4',
    uploadedAt: DateTime(2025, 5, 2, 21, 15),
    status: UploadStatus.completed,
    progress: 1.0,
    intensityScore: 92,
    matchScore: '3 - 1',
    tacticalSummary:
        'GoalSight controlled central zones with high-press triggers. Wide overloads created 6 high-value chances.',
  ),
  UploadJobModel(
    id: 'job-002',
    homeTeam: 'Sharks FC',
    awayTeam: 'GoalSight FC',
    competition: 'Premier League',
    venue: 'Shark Tank Stadium',
    matchDate: DateTime(2025, 4, 28),
    fileName: 'match_sharks_vs_goalsight_apr28.mp4',
    uploadedAt: DateTime(2025, 4, 28, 22, 40),
    status: UploadStatus.completed,
    progress: 1.0,
    intensityScore: 65,
    matchScore: '0 - 0',
    tacticalSummary:
        'Defensive solidity throughout. Mid-block held shape well; limited Sharks to 3 shots on target.',
  ),
  UploadJobModel(
    id: 'job-003',
    homeTeam: 'Lions City',
    awayTeam: 'GoalSight FC',
    competition: 'League Cup',
    venue: 'Lions Den',
    matchDate: DateTime(2025, 4, 22),
    fileName: 'cup_lions_vs_goalsight_apr22.mp4',
    uploadedAt: DateTime(2025, 4, 22, 20, 05),
    status: UploadStatus.completed,
    progress: 1.0,
    intensityScore: 78,
    matchScore: '1 - 2',
    tacticalSummary:
        'Strong second-half comeback. Tactical switch to 3-5-2 at HT created numerical advantage.',
  ),
  UploadJobModel(
    id: 'job-004',
    homeTeam: 'GoalSight FC',
    awayTeam: 'Panthers FC',
    competition: 'Premier League',
    venue: 'GoalSight Arena',
    matchDate: DateTime(2025, 4, 16),
    fileName: 'match_goalsight_vs_panthers_apr16.mp4',
    uploadedAt: DateTime(2025, 4, 16, 19, 30),
    status: UploadStatus.failed,
    progress: 0.34,
    failureReason: 'Video file corrupted at timestamp 42:18. Re-encode and retry.',
  ),
  UploadJobModel(
    id: 'job-005',
    homeTeam: 'Eagles Club',
    awayTeam: 'GoalSight FC',
    competition: 'Premier League',
    venue: 'Eagles Nest',
    matchDate: DateTime(2025, 4, 10),
    fileName: 'match_eagles_vs_goalsight_apr10.mp4',
    uploadedAt: DateTime(2025, 4, 10, 22, 15),
    status: UploadStatus.completed,
    progress: 1.0,
    intensityScore: 84,
    matchScore: '1 - 3',
    tacticalSummary:
        'Clinical counter-attacking performance. Fast transitions from back three led to all three goals.',
  ),
  UploadJobModel(
    id: 'job-006',
    homeTeam: 'GoalSight FC',
    awayTeam: 'Wolves United',
    competition: 'FA Cup',
    venue: 'GoalSight Arena',
    matchDate: DateTime(2025, 4, 4),
    fileName: 'facup_goalsight_vs_wolves_apr4.mp4',
    uploadedAt: DateTime(2025, 4, 4, 21, 50),
    status: UploadStatus.failed,
    progress: 0.0,
    failureReason: 'Unsupported resolution (8K). Please compress to 4K maximum.',
  ),
  UploadJobModel(
    id: 'job-007',
    homeTeam: 'GoalSight FC',
    awayTeam: 'Red Lions',
    competition: 'Premier League',
    venue: 'GoalSight Arena',
    matchDate: DateTime(2025, 3, 29),
    fileName: 'match_goalsight_vs_redlions_mar29.mp4',
    uploadedAt: DateTime(2025, 3, 29, 22, 10),
    status: UploadStatus.completed,
    progress: 1.0,
    intensityScore: 71,
    matchScore: '2 - 0',
    tacticalSummary:
        'Possession-dominant display with 64% control. Midfield pressed well above the halfway line.',
  ),
  UploadJobModel(
    id: 'job-008',
    homeTeam: 'GoalSight FC',
    awayTeam: 'Falcons United',
    competition: 'Premier League',
    venue: 'GoalSight Arena',
    matchDate: DateTime(2025, 5, 15),
    fileName: 'match_goalsight_vs_falcons_may15.mp4',
    uploadedAt: DateTime(2025, 5, 15, 23, 0),
    status: UploadStatus.processing,
    progress: 0.62,
    processingStage: ProcessingStage.generatingInsights,
  ),
];
