/// ---------------------------------------------------------------------------
/// GoalSight — Clubs Mock Data Provider
///
/// Simulates the exact structure returned by the backend API.
/// To go live: replace [mockClubsProvider] with an AsyncNotifierProvider
/// that fetches from Supabase and calls [ClubModel.fromJson].
/// ---------------------------------------------------------------------------

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/theme/app_theme.dart';
import '../../data/models/club_model.dart';

/// All clubs. Mirrors GET /api/clubs response shape.
final mockClubsProvider = Provider<List<ClubModel>>((ref) => _mockClubs);

/// Single club by ID. Mirrors GET /api/clubs/:id.
final mockClubByIdProvider = Provider.family<ClubModel?, String>((ref, id) {
  try {
    return _mockClubs.firstWhere((c) => c.id == id);
  } catch (_) {
    return null;
  }
});

// ─── Mock Club Data ───────────────────────────────────────────────────────────

const _mockClubs = [
  // ── 1. GoalSight FC (League Leaders) ────────────────────────────────────
  ClubModel(
    id: 'club_001',
    name: 'GoalSight FC',
    stadium: 'GoalSight Arena',
    league: 'GoalSight Premier League',
    primaryColor: AppColors.accentCyan,
    foundedYear: 1998,
    country: 'Egypt',
    coach: 'Ahmed Nour',
    playingStyle: 'High Press · 4-3-3',
    description: 'The most dominant club in the league, known for aggressive pressing and rapid transitions.',
    isFavorite: true,
    stats: ClubStats(
      matchesPlayed: 12,
      wins: 10,
      draws: 1,
      losses: 1,
      goalsScored: 30,
      goalsConceded: 8,
      ranking: 1,
      points: 31,
      cleanSheets: 7,
      avgPossession: 64,
      totalShots: 198,
      yellowCards: 12,
      redCards: 0,
    ),
    players: [
      ClubPlayer(
        id: 'cp1',
        name: 'Hassan Ali',
        position: 'CAM',
        rating: 9.1,
        nationality: '🇪🇬',
        age: 27,
        appearances: 12,
        goals: 8,
        assists: 10,
        marketValue: '€9.5M',
        isCaptain: true,
        performanceTier: PlayerPerformanceTier.elite,
        performanceSummary: 'Season-defining performances. Controls tempo, creates relentlessly — the league\'s best playmaker.',
      ),
      ClubPlayer(
        id: 'cp2',
        name: 'Mostafa Samir',
        position: 'LW',
        rating: 8.4,
        nationality: '🇪🇬',
        age: 24,
        appearances: 12,
        goals: 9,
        assists: 4,
        marketValue: '€6.2M',
        performanceTier: PlayerPerformanceTier.elite,
        performanceSummary: 'Electrifying on the left flank. Won 78% of dribble attempts. Scored in 6 consecutive matches.',
      ),
      ClubPlayer(
        id: 'cp3',
        name: 'Karim Wael',
        position: 'GK',
        rating: 8.0,
        nationality: '🇪🇬',
        age: 31,
        appearances: 12,
        cleanSheets: 7,
        marketValue: '€3.8M',
        performanceTier: PlayerPerformanceTier.elite,
        performanceSummary: '7 clean sheets and 38 saves. Commanding presence in the box — top 3 GK in the league.',
      ),
      ClubPlayer(
        id: 'cp4',
        name: 'Ziad Hamdy',
        position: 'CB',
        rating: 7.8,
        nationality: '🇪🇬',
        age: 29,
        appearances: 12,
        goals: 1,
        assists: 2,
        tackles: 54,
        marketValue: '€4.1M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Rock-solid centre-back. Wins 81% of aerial duels. Excellent in initiating build-up from deep.',
      ),
      ClubPlayer(
        id: 'cp5',
        name: 'Omar Fathy',
        position: 'RB',
        rating: 7.4,
        nationality: '🇪🇬',
        age: 23,
        appearances: 11,
        assists: 4,
        tackles: 38,
        marketValue: '€3.2M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Energetic right-back who contributes heavily in attack. Provided 4 assists via overlapping runs.',
      ),
      ClubPlayer(
        id: 'cp6',
        name: 'Tariq Ziad',
        position: 'DM',
        rating: 6.9,
        nationality: '🇪🇬',
        age: 26,
        appearances: 10,
        goals: 1,
        assists: 2,
        tackles: 47,
        marketValue: '€2.5M',
        performanceTier: PlayerPerformanceTier.average,
        performanceSummary: 'Disciplined in the defensive phase but loses possession too often under pressure. Improving.',
      ),
    ],
  ),

  // ── 2. Falcons United ────────────────────────────────────────────────────
  ClubModel(
    id: 'club_002',
    name: 'Falcons United',
    stadium: 'Sky Stadium',
    league: 'GoalSight Premier League',
    primaryColor: AppColors.primaryPurple,
    foundedYear: 2003,
    country: 'Egypt',
    coach: 'Samy Hassan',
    playingStyle: 'Balanced · 4-2-3-1',
    description: 'Consistent contenders built on solid defence and set-piece mastery.',
    stats: ClubStats(
      matchesPlayed: 12,
      wins: 7,
      draws: 4,
      losses: 1,
      goalsScored: 21,
      goalsConceded: 11,
      ranking: 2,
      points: 25,
      cleanSheets: 5,
      avgPossession: 52,
      totalShots: 156,
      yellowCards: 18,
      redCards: 1,
    ),
    players: [
      ClubPlayer(
        id: 'cp7',
        name: 'Adel Ragab',
        position: 'ST',
        rating: 8.3,
        nationality: '🇪🇬',
        age: 25,
        appearances: 12,
        goals: 11,
        assists: 3,
        marketValue: '€7.0M',
        isCaptain: true,
        performanceTier: PlayerPerformanceTier.elite,
        performanceSummary: 'Top scorer in the league. Lethal in the box — 11 goals from just 38 shots. Clinical finisher.',
      ),
      ClubPlayer(
        id: 'cp8',
        name: 'Youssef Ahmed',
        position: 'CM',
        rating: 7.6,
        nationality: '🇪🇬',
        age: 28,
        appearances: 12,
        goals: 2,
        assists: 6,
        tackles: 42,
        marketValue: '€3.9M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Engine of the midfield. High work rate, strong in the tackle, and creative in tight spaces.',
      ),
      ClubPlayer(
        id: 'cp9',
        name: 'Nasser Ibrahim',
        position: 'CB',
        rating: 7.9,
        nationality: '🇪🇬',
        age: 30,
        appearances: 12,
        goals: 2,
        assists: 0,
        tackles: 61,
        marketValue: '€4.5M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Commanding CB. Dominates set pieces at both ends. Scored 2 goals from corners this season.',
      ),
      ClubPlayer(
        id: 'cp10',
        name: 'Sherif Gamal',
        position: 'LB',
        rating: 6.7,
        nationality: '🇪🇬',
        age: 22,
        appearances: 10,
        assists: 2,
        tackles: 29,
        marketValue: '€1.8M',
        performanceTier: PlayerPerformanceTier.average,
        performanceSummary: 'Young full-back showing potential. Defensively shaky vs pacey wingers but improving match by match.',
      ),
      ClubPlayer(
        id: 'cp11',
        name: 'Mahmoud Saif',
        position: 'GK',
        rating: 7.5,
        nationality: '🇪🇬',
        age: 33,
        appearances: 12,
        cleanSheets: 5,
        marketValue: '€2.7M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Experienced shot-stopper. Excellent distribution and sweeping ability. Keeps the defence organised.',
      ),
    ],
  ),

  // ── 3. Lions City ────────────────────────────────────────────────────────
  ClubModel(
    id: 'club_003',
    name: 'Lions City',
    stadium: 'The Den',
    league: 'GoalSight Premier League',
    primaryColor: AppColors.warning,
    foundedYear: 1995,
    country: 'Egypt',
    coach: 'Khalid Mostafa',
    playingStyle: 'Direct Play · 4-4-2',
    description: 'Hard-working and physical — known for resilience and dangerous set pieces.',
    stats: ClubStats(
      matchesPlayed: 12,
      wins: 6,
      draws: 4,
      losses: 2,
      goalsScored: 19,
      goalsConceded: 14,
      ranking: 3,
      points: 22,
      cleanSheets: 4,
      avgPossession: 44,
      totalShots: 141,
      yellowCards: 24,
      redCards: 2,
    ),
    players: [
      ClubPlayer(
        id: 'cp12',
        name: 'Tamer Said',
        position: 'ST',
        rating: 8.0,
        nationality: '🇪🇬',
        age: 26,
        appearances: 12,
        goals: 9,
        assists: 2,
        marketValue: '€5.5M',
        isCaptain: true,
        performanceTier: PlayerPerformanceTier.elite,
        performanceSummary: 'Physical and technically gifted. Wins most aerial battles and brings teammates into play effectively.',
      ),
      ClubPlayer(
        id: 'cp13',
        name: 'Amr Khaled',
        position: 'AM',
        rating: 7.4,
        nationality: '🇪🇬',
        age: 24,
        appearances: 11,
        goals: 4,
        assists: 6,
        marketValue: '€3.6M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Creative link between midfield and attack. Provides key passes in tight areas with composure.',
      ),
      ClubPlayer(
        id: 'cp14',
        name: 'Walid Nour',
        position: 'CB',
        rating: 6.8,
        nationality: '🇪🇬',
        age: 32,
        appearances: 12,
        tackles: 48,
        marketValue: '€1.5M',
        performanceTier: PlayerPerformanceTier.average,
        performanceSummary: 'Experienced but losing a step. Strong positioning compensates for declining pace in most matches.',
      ),
    ],
  ),

  // ── 4. Sharks FC ─────────────────────────────────────────────────────────
  ClubModel(
    id: 'club_004',
    name: 'Sharks FC',
    stadium: 'Oceanic Park',
    league: 'GoalSight Premier League',
    primaryColor: AppColors.primaryBlue,
    foundedYear: 2008,
    country: 'Egypt',
    coach: 'Hany Zakaria',
    playingStyle: 'Mid Block · 4-1-4-1',
    description: 'Compact and organised — tough to beat at home, danger on the counter-attack.',
    stats: ClubStats(
      matchesPlayed: 12,
      wins: 5,
      draws: 4,
      losses: 3,
      goalsScored: 15,
      goalsConceded: 14,
      ranking: 4,
      points: 19,
      cleanSheets: 4,
      avgPossession: 48,
      totalShots: 128,
      yellowCards: 20,
      redCards: 1,
    ),
    players: [
      ClubPlayer(
        id: 'cp15',
        name: 'Omar Fathy',
        position: 'GK',
        rating: 8.1,
        nationality: '🇪🇬',
        age: 29,
        appearances: 12,
        cleanSheets: 4,
        marketValue: '€4.8M',
        isCaptain: true,
        performanceTier: PlayerPerformanceTier.elite,
        performanceSummary: 'Best goalkeeper in the league this season. 41 saves — the primary reason Sharks remain competitive.',
      ),
      ClubPlayer(
        id: 'cp16',
        name: 'Bassem Nabil',
        position: 'RW',
        rating: 7.6,
        nationality: '🇪🇬',
        age: 23,
        appearances: 12,
        goals: 6,
        assists: 3,
        marketValue: '€4.0M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Pacey winger who thrives on the counter. 6 goals, 3 assists — a constant danger in transition.',
      ),
      ClubPlayer(
        id: 'cp17',
        name: 'Ibrahim Sameh',
        position: 'CB',
        rating: 7.1,
        nationality: '🇪🇬',
        age: 28,
        appearances: 12,
        goals: 1,
        tackles: 55,
        marketValue: '€2.8M',
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Consistent in the defensive block. High tackle success rate and strong aerial ability.',
      ),
    ],
  ),

  // ── 5. Eagles Club ───────────────────────────────────────────────────────
  ClubModel(
    id: 'club_005',
    name: 'Eagles Club',
    stadium: 'High Peak Arena',
    league: 'GoalSight Premier League',
    primaryColor: AppColors.danger,
    foundedYear: 2001,
    country: 'Egypt',
    coach: 'Ramy Fares',
    playingStyle: 'Low Block · 5-4-1',
    description: 'Defensively organised with pacey attackers on the break — hard to dominate.',
    stats: ClubStats(
      matchesPlayed: 12,
      wins: 4,
      draws: 5,
      losses: 3,
      goalsScored: 13,
      goalsConceded: 16,
      ranking: 5,
      points: 17,
      cleanSheets: 3,
      avgPossession: 39,
      totalShots: 114,
      yellowCards: 28,
      redCards: 3,
    ),
    players: [
      ClubPlayer(
        id: 'cp18',
        name: 'Saad Magdy',
        position: 'ST',
        rating: 7.2,
        nationality: '🇪🇬',
        age: 27,
        appearances: 12,
        goals: 7,
        assists: 1,
        marketValue: '€3.3M',
        isCaptain: true,
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'Hard-working striker who holds the ball up and brings others into play. Scores most goals from set pieces.',
      ),
      ClubPlayer(
        id: 'cp19',
        name: 'Fady Emam',
        position: 'CM',
        rating: 6.5,
        nationality: '🇪🇬',
        age: 25,
        appearances: 11,
        goals: 1,
        assists: 4,
        tackles: 33,
        marketValue: '€1.9M',
        performanceTier: PlayerPerformanceTier.average,
        performanceSummary: 'Works hard to link play but struggles with final third execution. High pass completion in own half.',
      ),
    ],
  ),

  // ── 6. Panthers ──────────────────────────────────────────────────────────
  ClubModel(
    id: 'club_006',
    name: 'Panthers',
    stadium: 'Jungle Stadium',
    league: 'GoalSight Premier League',
    primaryColor: AppColors.accentGreen,
    foundedYear: 2010,
    country: 'Egypt',
    coach: 'Nader Ali',
    playingStyle: 'Counter-attack · 4-5-1',
    description: 'Young squad with high potential. Inconsistent but capable of beating anyone on their day.',
    stats: ClubStats(
      matchesPlayed: 12,
      wins: 3,
      draws: 3,
      losses: 6,
      goalsScored: 12,
      goalsConceded: 18,
      ranking: 6,
      points: 12,
      cleanSheets: 2,
      avgPossession: 42,
      totalShots: 109,
      yellowCards: 22,
      redCards: 1,
    ),
    players: [
      ClubPlayer(
        id: 'cp20',
        name: 'George Maher',
        position: 'LW',
        rating: 7.3,
        nationality: '🇪🇬',
        age: 22,
        appearances: 12,
        goals: 5,
        assists: 3,
        marketValue: '€2.6M',
        isCaptain: true,
        performanceTier: PlayerPerformanceTier.good,
        performanceSummary: 'The team\'s brightest talent. Rapid and direct — beats defenders with ease. Needs to improve consistency.',
      ),
      ClubPlayer(
        id: 'cp21',
        name: 'Andrew Nabil',
        position: 'GK',
        rating: 6.4,
        nationality: '🇪🇬',
        age: 30,
        appearances: 12,
        cleanSheets: 2,
        marketValue: '€1.2M',
        performanceTier: PlayerPerformanceTier.poor,
        performanceSummary: 'Struggled with shot-stopping this season. Conceded 18 goals — positional awareness needs work.',
      ),
    ],
  ),
];
